{{ config(materialized='table') }}



select O1.O_ORDERDATE AS ORDER_DATE,sum(O1.O_TOTALPRICE) AS cumulative_sales 
FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS" O1 INNER JOIN 
"SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS" O2 ON O1.O_ORDERKEY>=O2.O_ORDERKEY 
GROUP BY O1.O_ORDERDATE 
ORDER BY O1.O_ORDERDATE
